【確認待ち】Swiper を更新
vektor-inc/lightning pull request #1031
Opened 2023-06-01 02:38 UTC by drill-lancer

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://vws.vektor-inc.co.jp/forums/topic/top%e3%83%9a%e3%83%bc%e3%82%b8%e3%82%b9%e3%83%a9%e3%82%a4%e3%83%89%e3%82%b7%e3%83%a7%e3%83%bc%e3%81%8c%e3%82%bf%e3%83%86%e3%81%ab%e4%b8%a6%e3%82%93%e3%81%a7%e3%81%97%e3%81%be%e3%81%86

## どういう変更をしたか？

- 上記お問い合わせに対応（Windows で XAMPP を使用したとき、パスがURLに置換されなくておかしくなるバグを修正）
- Swiper を 9.3.2 に更新

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] Files changed (変更ファイル)の内容は目視で確認したか？
- [x] readme.txt に変更内容は書いたか？
- [x] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？
⇒大幅な変更はないため省略

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

- 実際に Windows ✕ XAMPP で確認
- スライダーブロックが正常に動くのを確認
- npm run phpunit が正常に動くのを確認

## 確認URL

ローカル環境

## レビュワーに回す前の確認事項

- [x] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

- 実際に Windows ✕ XAMPP で確認（できれば）
- スライダーブロックが正常に動くのを確認
- npm run phpunit が正常に動くのを確認

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-06-01 02:40 UTC, kurudrive commented
@drill-lancer ありがとうございます。バージョンは不具合修正なので 0.2.1 にしたいデス...。

2023-06-01 02:44 UTC, drill-lancer commented
@kurudrive 
Swiper 更新したので 0.3.0 ということで・・・
すっかり 0.3.0 ~ 0.3.1 とタグうちしたのと取り返しが付かない用なのでこれでお願いします。

2023-06-01 02:52 UTC, kurudrive commented
@drill-lancer ↓ これを使うのが正攻法説
https://developer.wordpress.org/reference/functions/wp_normalize_path/

2023-06-01 02:54 UTC, drill-lancer commented
@kurudrive 
・・・っぽいですね。修正します。

2023-06-01 03:08 UTC, drill-lancer commented
@kurudrive 
修正しました。

2023-06-02 05:06 UTC, kurudrive requested changes

2023-06-02 05:06 UTC, kurudrive commented on readme.txt
> +
[ G3 ][ Bug fix ] Fixed file reference bug of slider under specific environment such as Windows ( Update Swiper 9.3.2 )

2023-06-02 05:07 UTC, kurudrive requested changes

2023-06-02 05:07 UTC, kurudrive commented on readme.txt
> +[ G3 ] Update Swiper 9.3.2
```suggestion
[ G3 ] [ Bug fix ] Fixed file reference bug of slider under specific environment such as Windows ( Update Swiper 9.3.2 )
```

2023-06-02 05:08 UTC, merged

2023-06-02 06:09 UTC, kurudrive commented
@drill-lancer ありがとうございまっした！