Cover child element wide full
vektor-inc/lightning pull request #1049
Opened 2023-08-04 06:22 UTC by goutetsuguma

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/lightning/issues/1048

## どういう変更をしたか？

* このプルリクで変更した事を記載してください

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] Files changed (変更ファイル)の内容は目視で確認したか？
- [ ] readme.txt に変更内容は書いたか？
- [ ] 本当にちゃんと確認をしたか？

## プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。

- [ ] 書けそうなテストは書いたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

*
*
*

## 確認URL

（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）

## レビュワーに回す前の確認事項

- [ ] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## レビュワー確認方法・確認内容など

レビュワーがどういう手順で何を確認して欲しいかを記載してください。

*
*
*

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2023-08-06 19:28 UTC, kurudrive requested changes
@goutetsuguma ありがとうございます。

.wp-block-cover-image ってどうやったら付きます？
あと、カバーで overflow: clip; がないと困る場面って再現できます？

* :is() で出力コードが少なくなるように
* *> を追加してなるべく今回の上書きが少なるように

2023-08-06 19:28 UTC, kurudrive commented on _g3/assets/_scss/block/_block.scss
> +.wp-block-cover-image:has(.alignfull){
```suggestion
:is(.wp-block-cover,.wp-block-cover-image):has(:where(* >:is(.alignwide,.alignfull))){
```

2023-08-06 19:28 UTC, kurudrive commented on _g2/assets/_scss/block/_block_editor.scss
> +	.wp-block-cover-image:has(div[data-align=full]){
```suggestion
	:is(.wp-block-cover,.wp-block-cover-image):has(* > :is(div[data-align=wide]),div[data-align=full]){
```

2023-08-06 19:28 UTC, kurudrive commented on _g3/assets/_scss/block/_block-editor.scss
> +	.wp-block-cover-image:has(div[data-align=full]){
```suggestion
	:is(.wp-block-cover,.wp-block-cover-image):has(* > :is(div[data-align=wide]),div[data-align=full]){
```

2023-08-06 19:28 UTC, kurudrive commented on _g2/assets/_scss/block/_block.scss
> +.wp-block-cover-image:has(.alignfull){
```suggestion
:is(.wp-block-cover,.wp-block-cover-image):has(:where(* >:is(.alignwide,.alignfull))){
```

2023-08-07 04:42 UTC, goutetsuguma commented
@kurudrive 

> .wp-block-cover-image ってどうやったら付きます？

→ 確認しましたところ、どこにも付かないようでしたので、cssのクラス名の部分は削除しました。

> あと、カバーで overflow: clip; がないと困る場面って再現できます？

→ 普通に使用している場面ではoverflow: clip;がないと困る場面はなさそうに思います（強いてゆうならCSSでhover時に背景の画像が拡大するようなCSSカスタマイズをした場合に、overflow: clip;になっていると良いなと思うくらいでした）

> :is() で出力コードが少なくなるように
> *> を追加してなるべく今回の上書きが少なるように

ありがとうございます！勉強になりました！！！！
`:has( :is(　)) `みたいに`:has`の中に`:is ()`とか書けるのですね、、！知りませんでした、、！

【質問しても良いでしょうか】
ご提案いただいたコードの中に
`:has(:where(* >:is(.alignwide,.alignfull))){`　の部分の `:where `の部分は必要なのでしょうか、、？
ちょっとわからなかったので、無くても問題なさそうに思い、今回ははぶきました。

2023-08-07 05:56 UTC, kurudrive commented
@goutetsuguma 

> :where の部分は必要なのでしょうか

あぁ、 :where を入れた方が詳細度が下がるからユーザーが上書きしやすくなる...と書きたかったんだけど、試したら :where なくても普通に
.wp-block-cover:has(.alignwide){
	overflow: clip;
}
で上書きできたからなくて良いデス...。

2023-08-07 07:00 UTC, kurudrive approved these changes

2023-08-07 07:09 UTC, merged